// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount         float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitOrderRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubmitOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // COMMITTED, ABORTED, PENDING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SubmitOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusRequest) Reset() {
	*x = OrderStatusRequest{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusRequest) ProtoMessage() {}

func (x *OrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusRequest.ProtoReflect.Descriptor instead.
func (*OrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type OrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusResponse) Reset() {
	*x = OrderStatusResponse{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusResponse) ProtoMessage() {}

func (x *OrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OrderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PrepareRequest_Inventory
	//	*PrepareRequest_Payment
	Payload       isPrepareRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PrepareRequest) GetPayload() isPrepareRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PrepareRequest) GetInventory() *InventoryPayload {
	if x != nil {
		if x, ok := x.Payload.(*PrepareRequest_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *PrepareRequest) GetPayment() *PaymentPayload {
	if x != nil {
		if x, ok := x.Payload.(*PrepareRequest_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

type isPrepareRequest_Payload interface {
	isPrepareRequest_Payload()
}

type PrepareRequest_Inventory struct {
	Inventory *InventoryPayload `protobuf:"bytes,2,opt,name=inventory,proto3,oneof"`
}

type PrepareRequest_Payment struct {
	Payment *PaymentPayload `protobuf:"bytes,3,opt,name=payment,proto3,oneof"`
}

func (*PrepareRequest_Inventory) isPrepareRequest_Payload() {}

func (*PrepareRequest_Payment) isPrepareRequest_Payload() {}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	VoteYes       bool                   `protobuf:"varint,2,opt,name=vote_yes,json=voteYes,proto3" json:"vote_yes,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PrepareResponse) GetVoteYes() bool {
	if x != nil {
		return x.VoteYes
	}
	return false
}

func (x *PrepareResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InventoryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryPayload) Reset() {
	*x = InventoryPayload{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryPayload) ProtoMessage() {}

func (x *InventoryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryPayload.ProtoReflect.Descriptor instead.
func (*InventoryPayload) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryPayload) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryPayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PaymentPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentPayload) Reset() {
	*x = PaymentPayload{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPayload) ProtoMessage() {}

func (x *PaymentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPayload.ProtoReflect.Descriptor instead.
func (*PaymentPayload) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentPayload) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *CommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *CommitResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *AbortRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *AbortResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AbortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *StatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *StatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// 3PC messages
type CanCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CanCommitRequest_Inventory
	//	*CanCommitRequest_Payment
	Payload       isCanCommitRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanCommitRequest) Reset() {
	*x = CanCommitRequest{}
	mi := &file_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanCommitRequest) ProtoMessage() {}

func (x *CanCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanCommitRequest.ProtoReflect.Descriptor instead.
func (*CanCommitRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *CanCommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CanCommitRequest) GetPayload() isCanCommitRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CanCommitRequest) GetInventory() *InventoryPayload {
	if x != nil {
		if x, ok := x.Payload.(*CanCommitRequest_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *CanCommitRequest) GetPayment() *PaymentPayload {
	if x != nil {
		if x, ok := x.Payload.(*CanCommitRequest_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

type isCanCommitRequest_Payload interface {
	isCanCommitRequest_Payload()
}

type CanCommitRequest_Inventory struct {
	Inventory *InventoryPayload `protobuf:"bytes,2,opt,name=inventory,proto3,oneof"`
}

type CanCommitRequest_Payment struct {
	Payment *PaymentPayload `protobuf:"bytes,3,opt,name=payment,proto3,oneof"`
}

func (*CanCommitRequest_Inventory) isCanCommitRequest_Payload() {}

func (*CanCommitRequest_Payment) isCanCommitRequest_Payload() {}

type CanCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CanCommit     bool                   `protobuf:"varint,2,opt,name=can_commit,json=canCommit,proto3" json:"can_commit,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanCommitResponse) Reset() {
	*x = CanCommitResponse{}
	mi := &file_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanCommitResponse) ProtoMessage() {}

func (x *CanCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanCommitResponse.ProtoReflect.Descriptor instead.
func (*CanCommitResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *CanCommitResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CanCommitResponse) GetCanCommit() bool {
	if x != nil {
		return x.CanCommit
	}
	return false
}

func (x *CanCommitResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PreCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCommitRequest) Reset() {
	*x = PreCommitRequest{}
	mi := &file_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCommitRequest) ProtoMessage() {}

func (x *PreCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCommitRequest.ProtoReflect.Descriptor instead.
func (*PreCommitRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *PreCommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PreCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCommitResponse) Reset() {
	*x = PreCommitResponse{}
	mi := &file_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCommitResponse) ProtoMessage() {}

func (x *PreCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCommitResponse.ProtoReflect.Descriptor instead.
func (*PreCommitResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *PreCommitResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PreCommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DoCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoCommitRequest) Reset() {
	*x = DoCommitRequest{}
	mi := &file_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoCommitRequest) ProtoMessage() {}

func (x *DoCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoCommitRequest.ProtoReflect.Descriptor instead.
func (*DoCommitRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{18}
}

func (x *DoCommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type DoCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoCommitResponse) Reset() {
	*x = DoCommitResponse{}
	mi := &file_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoCommitResponse) ProtoMessage() {}

func (x *DoCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoCommitResponse.ProtoReflect.Descriptor instead.
func (*DoCommitResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *DoCommitResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DoCommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Chaos stats messages
type ChaosStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaosStatsRequest) Reset() {
	*x = ChaosStatsRequest{}
	mi := &file_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosStatsRequest) ProtoMessage() {}

func (x *ChaosStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosStatsRequest.ProtoReflect.Descriptor instead.
func (*ChaosStatsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{20}
}

type ChaosStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drops         int64                  `protobuf:"varint,1,opt,name=drops,proto3" json:"drops,omitempty"`
	Delays        int64                  `protobuf:"varint,2,opt,name=delays,proto3" json:"delays,omitempty"`
	Phantoms      int64                  `protobuf:"varint,3,opt,name=phantoms,proto3" json:"phantoms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaosStatsResponse) Reset() {
	*x = ChaosStatsResponse{}
	mi := &file_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosStatsResponse) ProtoMessage() {}

func (x *ChaosStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosStatsResponse.ProtoReflect.Descriptor instead.
func (*ChaosStatsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{21}
}

func (x *ChaosStatsResponse) GetDrops() int64 {
	if x != nil {
		return x.Drops
	}
	return 0
}

func (x *ChaosStatsResponse) GetDelays() int64 {
	if x != nil {
		return x.Delays
	}
	return 0
}

func (x *ChaosStatsResponse) GetPhantoms() int64 {
	if x != nil {
		return x.Phantoms
	}
	return 0
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x02pb\"\xa3\x01\n" +
	"\x12SubmitOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"T\n" +
	"\x13SubmitOrderResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\x12OrderStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"T\n" +
	"\x13OrderStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa8\x01\n" +
	"\x0ePrepareRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x124\n" +
	"\tinventory\x18\x02 \x01(\v2\x14.pb.InventoryPayloadH\x00R\tinventory\x12.\n" +
	"\apayment\x18\x03 \x01(\v2\x12.pb.PaymentPayloadH\x00R\apaymentB\t\n" +
	"\apayload\"k\n" +
	"\x0fPrepareResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x19\n" +
	"\bvote_yes\x18\x02 \x01(\bR\avoteYes\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"G\n" +
	"\x10InventoryPayload\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"A\n" +
	"\x0ePaymentPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"6\n" +
	"\rCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"Q\n" +
	"\x0eCommitResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"5\n" +
	"\fAbortRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"P\n" +
	"\rAbortResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"6\n" +
	"\rStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"M\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xaa\x01\n" +
	"\x10CanCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x124\n" +
	"\tinventory\x18\x02 \x01(\v2\x14.pb.InventoryPayloadH\x00R\tinventory\x12.\n" +
	"\apayment\x18\x03 \x01(\v2\x12.pb.PaymentPayloadH\x00R\apaymentB\t\n" +
	"\apayload\"q\n" +
	"\x11CanCommitResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"can_commit\x18\x02 \x01(\bR\tcanCommit\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"9\n" +
	"\x10PreCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"T\n" +
	"\x11PreCommitResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"8\n" +
	"\x0fDoCommitRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"S\n" +
	"\x10DoCommitResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x13\n" +
	"\x11ChaosStatsRequest\"^\n" +
	"\x12ChaosStatsResponse\x12\x14\n" +
	"\x05drops\x18\x01 \x01(\x03R\x05drops\x12\x16\n" +
	"\x06delays\x18\x02 \x01(\x03R\x06delays\x12\x1a\n" +
	"\bphantoms\x18\x03 \x01(\x03R\bphantoms2\xdb\x01\n" +
	"\x16TransactionCoordinator\x12>\n" +
	"\vSubmitOrder\x12\x16.pb.SubmitOrderRequest\x1a\x17.pb.SubmitOrderResponse\x12A\n" +
	"\x0eGetOrderStatus\x12\x16.pb.OrderStatusRequest\x1a\x17.pb.OrderStatusResponse\x12>\n" +
	"\rGetChaosStats\x12\x15.pb.ChaosStatsRequest\x1a\x16.pb.ChaosStatsResponse2\x8a\x03\n" +
	"\x16TransactionParticipant\x122\n" +
	"\aPrepare\x12\x12.pb.PrepareRequest\x1a\x13.pb.PrepareResponse\x12/\n" +
	"\x06Commit\x12\x11.pb.CommitRequest\x1a\x12.pb.CommitResponse\x12,\n" +
	"\x05Abort\x12\x10.pb.AbortRequest\x1a\x11.pb.AbortResponse\x122\n" +
	"\tGetStatus\x12\x11.pb.StatusRequest\x1a\x12.pb.StatusResponse\x128\n" +
	"\tCanCommit\x12\x14.pb.CanCommitRequest\x1a\x15.pb.CanCommitResponse\x128\n" +
	"\tPreCommit\x12\x14.pb.PreCommitRequest\x1a\x15.pb.PreCommitResponse\x125\n" +
	"\bDoCommit\x12\x13.pb.DoCommitRequest\x1a\x14.pb.DoCommitResponseB\x1dZ\x1bdistributed-transactions/pbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_transaction_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),  // 0: pb.SubmitOrderRequest
	(*SubmitOrderResponse)(nil), // 1: pb.SubmitOrderResponse
	(*OrderStatusRequest)(nil),  // 2: pb.OrderStatusRequest
	(*OrderStatusResponse)(nil), // 3: pb.OrderStatusResponse
	(*PrepareRequest)(nil),      // 4: pb.PrepareRequest
	(*PrepareResponse)(nil),     // 5: pb.PrepareResponse
	(*InventoryPayload)(nil),    // 6: pb.InventoryPayload
	(*PaymentPayload)(nil),      // 7: pb.PaymentPayload
	(*CommitRequest)(nil),       // 8: pb.CommitRequest
	(*CommitResponse)(nil),      // 9: pb.CommitResponse
	(*AbortRequest)(nil),        // 10: pb.AbortRequest
	(*AbortResponse)(nil),       // 11: pb.AbortResponse
	(*StatusRequest)(nil),       // 12: pb.StatusRequest
	(*StatusResponse)(nil),      // 13: pb.StatusResponse
	(*CanCommitRequest)(nil),    // 14: pb.CanCommitRequest
	(*CanCommitResponse)(nil),   // 15: pb.CanCommitResponse
	(*PreCommitRequest)(nil),    // 16: pb.PreCommitRequest
	(*PreCommitResponse)(nil),   // 17: pb.PreCommitResponse
	(*DoCommitRequest)(nil),     // 18: pb.DoCommitRequest
	(*DoCommitResponse)(nil),    // 19: pb.DoCommitResponse
	(*ChaosStatsRequest)(nil),   // 20: pb.ChaosStatsRequest
	(*ChaosStatsResponse)(nil),  // 21: pb.ChaosStatsResponse
}
var file_transaction_proto_depIdxs = []int32{
	6,  // 0: pb.PrepareRequest.inventory:type_name -> pb.InventoryPayload
	7,  // 1: pb.PrepareRequest.payment:type_name -> pb.PaymentPayload
	6,  // 2: pb.CanCommitRequest.inventory:type_name -> pb.InventoryPayload
	7,  // 3: pb.CanCommitRequest.payment:type_name -> pb.PaymentPayload
	0,  // 4: pb.TransactionCoordinator.SubmitOrder:input_type -> pb.SubmitOrderRequest
	2,  // 5: pb.TransactionCoordinator.GetOrderStatus:input_type -> pb.OrderStatusRequest
	20, // 6: pb.TransactionCoordinator.GetChaosStats:input_type -> pb.ChaosStatsRequest
	4,  // 7: pb.TransactionParticipant.Prepare:input_type -> pb.PrepareRequest
	8,  // 8: pb.TransactionParticipant.Commit:input_type -> pb.CommitRequest
	10, // 9: pb.TransactionParticipant.Abort:input_type -> pb.AbortRequest
	12, // 10: pb.TransactionParticipant.GetStatus:input_type -> pb.StatusRequest
	14, // 11: pb.TransactionParticipant.CanCommit:input_type -> pb.CanCommitRequest
	16, // 12: pb.TransactionParticipant.PreCommit:input_type -> pb.PreCommitRequest
	18, // 13: pb.TransactionParticipant.DoCommit:input_type -> pb.DoCommitRequest
	1,  // 14: pb.TransactionCoordinator.SubmitOrder:output_type -> pb.SubmitOrderResponse
	3,  // 15: pb.TransactionCoordinator.GetOrderStatus:output_type -> pb.OrderStatusResponse
	21, // 16: pb.TransactionCoordinator.GetChaosStats:output_type -> pb.ChaosStatsResponse
	5,  // 17: pb.TransactionParticipant.Prepare:output_type -> pb.PrepareResponse
	9,  // 18: pb.TransactionParticipant.Commit:output_type -> pb.CommitResponse
	11, // 19: pb.TransactionParticipant.Abort:output_type -> pb.AbortResponse
	13, // 20: pb.TransactionParticipant.GetStatus:output_type -> pb.StatusResponse
	15, // 21: pb.TransactionParticipant.CanCommit:output_type -> pb.CanCommitResponse
	17, // 22: pb.TransactionParticipant.PreCommit:output_type -> pb.PreCommitResponse
	19, // 23: pb.TransactionParticipant.DoCommit:output_type -> pb.DoCommitResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_transaction_proto_msgTypes[4].OneofWrappers = []any{
		(*PrepareRequest_Inventory)(nil),
		(*PrepareRequest_Payment)(nil),
	}
	file_transaction_proto_msgTypes[14].OneofWrappers = []any{
		(*CanCommitRequest_Inventory)(nil),
		(*CanCommitRequest_Payment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
